[project]
name = "taskbounty"
description = "Unique voting contract for project 07"
authors = ["solidworkssa"]
telemetry = false
cache_dir = ".cache"

[contracts.taskbounty]
path = "contracts/taskbounty.clar"

[repl.analysis]
passes = ["check_checker"]
